// Command mdview-server is the relay process spawned by the Neovim plugin.
// It authenticates a single trusted Neovim instance (via a shared token
// generated by the Lua side), accepts raw markdown text over HTTP, and fans
// it out over WebSocket to browser tabs watching the same document. It never
// renders markdown or touches HTML — that happens entirely client-side in
// the WASM module, so this process has no code path that turns untrusted
// document content into markup.
package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"log"
	"mime"
	"net/http"

	"nhooyr.io/websocket"

	"github.com/StefanBartl/mdview.nvim/native/server/internal/relay"
)

const maxUpdateBodyBytes = 32 << 20 // 32 MiB ceiling against runaway request bodies
const maxScrollBodyBytes = 256      // scroll payload is just "<line>/<total>"

// scrollMessagePrefix tags a WebSocket message as a scroll-position ping
// rather than document content, so the client's single onmessage handler can
// tell them apart without a JSON envelope. \x01 is a non-printable control
// byte that can never appear in typed Markdown text, so there's no
// ambiguity with real content.
const scrollMessagePrefix = "\x01"

// wsConn adapts a *websocket.Conn to relay.Conn so relay.Registry stays
// decoupled from the WebSocket library and can be tested without a network.
type wsConn struct {
	ctx context.Context
	c   *websocket.Conn
}

func (w wsConn) Send(payload []byte) error {
	return w.c.Write(w.ctx, websocket.MessageText, payload)
}

func main() {
	preferredPort := flag.Int("port", 43219, "preferred port to bind on 127.0.0.1")
	webRoot := flag.String("web-root", "dist/client", "directory containing the built client bundle")
	token := flag.String("token", "", "shared session token generated by the Lua caller (required)")
	flag.Parse()

	if *token == "" {
		log.Fatal("--token is required: the Lua caller must generate and pass a session token")
	}

	port, err := relay.FindFreePort(*preferredPort)
	if err != nil {
		log.Fatalf("failed to find free port: %v", err)
	}

	registry := relay.NewRegistry()
	mime.AddExtensionType(".wasm", "application/wasm")
	fileServer := http.FileServer(http.Dir(*webRoot))

	mux := http.NewServeMux()
	mux.HandleFunc("/health", handleHealth)
	mux.HandleFunc("/update", handleUpdate(registry, *token))
	mux.HandleFunc("/scroll", handleScroll(registry, *token))
	mux.HandleFunc("/ws", handleWS(registry, *token, port))
	mux.Handle("/", fileServer)

	addr := fmt.Sprintf("127.0.0.1:%d", port)
	// Lua's runner matches this exact line to discover the port; keep the format stable.
	fmt.Printf("Running on http://localhost:%d\n", port)
	fmt.Printf("ws endpoint: ws://localhost:%d/ws\n", port)

	if err := http.ListenAndServe(addr, mux); err != nil {
		log.Fatalf("server error: %v", err)
	}
}

func handleHealth(w http.ResponseWriter, _ *http.Request) {
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte("ok"))
}

// handleUpdate accepts the current raw text of a document from the trusted
// Lua process and fans it out to every browser tab watching that key.
func handleUpdate(registry *relay.Registry, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		key := r.URL.Query().Get("key")
		if key == "" {
			http.Error(w, "missing key", http.StatusBadRequest)
			return
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, maxUpdateBodyBytes))
		if err != nil {
			http.Error(w, "failed to read body", http.StatusBadRequest)
			return
		}
		registry.Broadcast(key, body)
		w.WriteHeader(http.StatusNoContent)
	}
}

// handleScroll accepts a "<line>/<total>" cursor-position ping from the
// trusted Lua process and fans it out to every browser tab watching that
// key, tagged with scrollMessagePrefix. Unlike handleUpdate, this does NOT
// update the room's "last content" (BroadcastEphemeral) — a scroll ping is a
// transient signal, not something a newly-joined tab should be seeded with
// in place of the actual document.
func handleScroll(registry *relay.Registry, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		key := r.URL.Query().Get("key")
		if key == "" {
			http.Error(w, "missing key", http.StatusBadRequest)
			return
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, maxScrollBodyBytes))
		if err != nil {
			http.Error(w, "failed to read body", http.StatusBadRequest)
			return
		}
		registry.BroadcastEphemeral(key, append([]byte(scrollMessagePrefix), body...))
		w.WriteHeader(http.StatusNoContent)
	}
}

// handleWS upgrades a browser connection after validating both the Origin
// header (rejects DNS-rebinding / cross-site WebSocket hijacking) and the
// shared token (rejects any process that isn't the plugin's own browser
// tab), then joins the connection to the room for its document key.
func handleWS(registry *relay.Registry, token string, port int) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !relay.IsAllowedOrigin(r.Header.Get("Origin"), port) {
			http.Error(w, "forbidden origin", http.StatusForbidden)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		key := r.URL.Query().Get("key")
		if key == "" {
			http.Error(w, "missing key", http.StatusBadRequest)
			return
		}

		c, err := websocket.Accept(w, r, &websocket.AcceptOptions{
			OriginPatterns: []string{"*"}, // Origin already validated above
		})
		if err != nil {
			return
		}
		defer c.CloseNow()

		ctx := r.Context()
		conn := wsConn{ctx: ctx, c: c}
		registry.Join(key, conn)
		defer registry.Leave(key, conn)

		if payload, ok := registry.LastPayload(key); ok {
			if err := conn.Send(payload); err != nil {
				return
			}
		}

		// Receive-only from the browser's side; all content flows in via POST
		// /update. Reading here just detects disconnects so we clean up the room.
		for {
			if _, _, err := c.Read(ctx); err != nil {
				return
			}
		}
	}
}
