// Command mdview-server is the relay process spawned by the Neovim plugin.
// It authenticates a single trusted Neovim instance (via a shared token
// generated by the Lua side), accepts raw markdown text over HTTP, and fans
// it out over WebSocket to browser tabs watching the same document. It never
// renders markdown or touches HTML — that happens entirely client-side in
// the WASM module, so this process has no code path that turns untrusted
// document content into markup.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"mime"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"nhooyr.io/websocket"

	"github.com/StefanBartl/mdview.nvim/native/server/internal/relay"
	"github.com/StefanBartl/mdview.nvim/native/server/internal/source"
)

const maxUpdateBodyBytes = 32 << 20 // 32 MiB ceiling against runaway request bodies
const maxScrollBodyBytes = 256      // scroll payload is just "<line>/<total>"

// scrollMessagePrefix tags a WebSocket message as a scroll-position ping
// rather than document content, so the client's single onmessage handler can
// tell them apart without a JSON envelope. \x01 is a non-printable control
// byte that can never appear in typed Markdown text, so there's no
// ambiguity with real content.
const scrollMessagePrefix = "\x01"

// closeMessagePrefix tags a WebSocket message as a "close this tab now" signal.
// The client calls window.close() on receipt. Used to cooperatively close
// preview tabs in the "default" browser open_mode, where mdview holds no OS
// process handle for the tab and so can't close it any other way. \x02, like
// \x01, is a control byte that can never appear in typed Markdown.
const closeMessagePrefix = "\x02"

// docMessagePrefix tags a WebSocket message as "the previewed document changed
// to <path>", so the client can maintain browser history (push a history entry
// per document, so Back/Forward work). \x04 is a control byte that can't appear
// in typed Markdown.
const docMessagePrefix = "\x04"

// controlMessagePrefix tags a WebSocket message as a live preview-control update
// (a small JSON object, e.g. {"cursor":"caret"} or {"zoom":1.2}), so runtime
// commands like :MDViewCursor and :MDViewZoom can change the open tab without a
// reload. \x05 is a control byte that can't appear in typed Markdown.
const controlMessagePrefix = "\x05"

// wsConn adapts a *websocket.Conn to relay.Conn so relay.Registry stays
// decoupled from the WebSocket library and can be tested without a network.
type wsConn struct {
	ctx context.Context
	c   *websocket.Conn
}

func (w wsConn) Send(payload []byte) error {
	return w.c.Write(w.ctx, websocket.MessageText, payload)
}

func main() {
	preferredPort := flag.Int("port", 43219, "preferred port to bind on 127.0.0.1")
	webRoot := flag.String("web-root", "dist/client", "directory containing the built client bundle")
	token := flag.String("token", "", "shared session token generated by the Lua caller (required unless --watch)")
	webtransport := flag.Bool("webtransport", false, "also serve an opt-in WebTransport (HTTP/3) endpoint on the same port")
	watch := flag.String("watch", "", "standalone mode: watch this Markdown file for changes instead of waiting for Neovim to POST /update")
	open := flag.Bool("open", true, "standalone mode only: open the preview in the default browser on start")
	theme := flag.String("theme", "github", "standalone mode only: preview theme passed to the client")
	highlighter := flag.String("hl", "hljs", "standalone mode only: code-fence highlighter passed to the client (hljs|shiki|none)")
	flag.Parse()

	// Standalone mode has no Lua side to mint a token, so the process mints its
	// own. Everything downstream (auth, origin checks, loopback-only binding) is
	// unchanged — only who generated the secret differs.
	standalone := *watch != ""
	if *token == "" {
		if !standalone {
			log.Fatal("--token is required: the Lua caller must generate and pass a session token")
		}
		generated, err := relay.GenerateToken()
		if err != nil {
			log.Fatalf("failed to generate session token: %v", err)
		}
		*token = generated
	}

	var watchPath string
	if standalone {
		abs, err := filepath.Abs(*watch)
		if err != nil {
			log.Fatalf("failed to resolve --watch path %q: %v", *watch, err)
		}
		if _, err := os.Stat(abs); err != nil {
			log.Fatalf("cannot watch %s: %v", abs, err)
		}
		watchPath = abs
	}

	port, err := relay.FindFreePort(*preferredPort)
	if err != nil {
		log.Fatalf("failed to find free port: %v", err)
	}

	registry := relay.NewRegistry()
	navQueue := relay.NewNavQueue()
	scrollBox := relay.NewScrollBox()
	mime.AddExtensionType(".wasm", "application/wasm")
	fileServer := http.FileServer(http.Dir(*webRoot))

	mux := http.NewServeMux()
	mux.HandleFunc("/health", handleHealth)
	mux.HandleFunc("/update", handleUpdate(registry, *token))
	mux.HandleFunc("/scroll", handleScroll(registry, *token))
	mux.HandleFunc("/doc", handleDoc(registry, *token))
	mux.HandleFunc("/control", handleControl(registry, *token))
	mux.HandleFunc("/diff", handleDiff(registry, *token))
	mux.HandleFunc("/close", handleClose(registry, *token))
	mux.HandleFunc("/nav", handleNav(navQueue, *token))
	mux.HandleFunc("/scrollback", handleScrollback(scrollBox, *token))
	mux.HandleFunc("/clientlog", handleClientLog(*token))
	mux.HandleFunc("/ws", handleWS(registry, *token, port))
	mux.Handle("/", fileServer)

	addr := fmt.Sprintf("127.0.0.1:%d", port)
	// Lua's runner matches this exact line to discover the port; keep the format stable.
	fmt.Printf("Running on http://localhost:%d\n", port)
	fmt.Printf("ws endpoint: ws://localhost:%d/ws\n", port)

	// Standalone mode: start the file watcher as a second content source and
	// print (optionally open) the preview URL, since there is no Neovim here to
	// build it. The watcher feeds registry.Broadcast — the same call the
	// /update handler makes — so nothing downstream of the registry can tell
	// the two modes apart.
	if standalone {
		key := filepath.ToSlash(watchPath)
		previewURL := fmt.Sprintf("http://localhost:%d/?key=%s&token=%s&theme=%s&hl=%s",
			port,
			url.QueryEscape(key),
			url.QueryEscape(*token),
			url.QueryEscape(*theme),
			url.QueryEscape(*highlighter),
		)
		fmt.Printf("watching: %s\n", watchPath)
		fmt.Printf("preview: %s\n", previewURL)

		go source.Watch(registry, key, watchPath, source.DefaultInterval, nil)

		if *open {
			if err := openBrowser(previewURL); err != nil {
				fmt.Printf("[watch] %v — open the preview URL above manually\n", err)
			}
		}
	}

	// Opt-in WebTransport (HTTP/3 over UDP on the same port). Generate a
	// short-lived self-signed cert and print its SHA-256 so the Lua side can
	// pass it to the browser as serverCertificateHashes. Failure here is
	// non-fatal — the client falls back to WebSocket.
	if *webtransport {
		cert, hash, err := relay.GenerateWebTransportCert()
		if err != nil {
			fmt.Printf("[webtransport] cert generation failed: %v (falling back to WebSocket only)\n", err)
		} else {
			// The Lua runner parses this exact line for the cert hash.
			fmt.Printf("wt cert-hash: %s\n", hash)
			startWebTransport(addr, cert, registry, *token)
		}
	}

	if err := http.ListenAndServe(addr, mux); err != nil {
		log.Fatalf("server error: %v", err)
	}
}

func handleHealth(w http.ResponseWriter, _ *http.Request) {
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte("ok"))
}

const maxClientLogBytes = 8 << 10 // 8 KiB per client log line

// handleClientLog lets the browser client report its own diagnostics
// (connection status, render/theme errors) back to the process. The line is
// printed to stdout with a "[client]" tag; the Lua runner captures the
// relay's stdout into the mdview log buffer, so browser-side problems show up
// in :MDViewShowWebLogs / :MDViewDiagnose without opening devtools. Purely a
// diagnostics sink — it never affects rendering or the room state.
func handleClientLog(token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, maxClientLogBytes))
		if err != nil {
			http.Error(w, "failed to read body", http.StatusBadRequest)
			return
		}
		// One line, control chars stripped, so a hostile page can't inject
		// fake log lines into the captured stream.
		line := strings.Map(func(rr rune) rune {
			if rr == '\n' || rr == '\r' {
				return ' '
			}
			return rr
		}, string(body))
		fmt.Printf("[client] %s\n", line)
		w.WriteHeader(http.StatusNoContent)
	}
}

// handleUpdate accepts the current raw text of a document from the trusted
// Lua process and fans it out to every browser tab watching that key.
func handleUpdate(registry *relay.Registry, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		key := r.URL.Query().Get("key")
		if key == "" {
			http.Error(w, "missing key", http.StatusBadRequest)
			return
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, maxUpdateBodyBytes))
		if err != nil {
			http.Error(w, "failed to read body", http.StatusBadRequest)
			return
		}
		registry.Broadcast(key, body)
		w.WriteHeader(http.StatusNoContent)
	}
}

// handleScroll accepts a "<line>/<total>" cursor-position ping from the
// trusted Lua process and fans it out to every browser tab watching that
// key, tagged with scrollMessagePrefix. Unlike handleUpdate, this does NOT
// update the room's "last content" (BroadcastEphemeral) — a scroll ping is a
// transient signal, not something a newly-joined tab should be seeded with
// in place of the actual document.
func handleScroll(registry *relay.Registry, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		key := r.URL.Query().Get("key")
		if key == "" {
			http.Error(w, "missing key", http.StatusBadRequest)
			return
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, maxScrollBodyBytes))
		if err != nil {
			http.Error(w, "failed to read body", http.StatusBadRequest)
			return
		}
		registry.BroadcastEphemeral(key, append([]byte(scrollMessagePrefix), body...))
		w.WriteHeader(http.StatusNoContent)
	}
}

const maxDocBodyBytes = 8 << 10 // a document path

// handleDoc broadcasts a "previewed document changed" signal (the new document
// path) to key's room, tagged with docMessagePrefix. Ephemeral like /scroll —
// a transient signal, not the room's content. The client uses it to push a
// browser-history entry so Back/Forward navigate between documents.
func handleDoc(registry *relay.Registry, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		key := r.URL.Query().Get("key")
		if key == "" {
			http.Error(w, "missing key", http.StatusBadRequest)
			return
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, maxDocBodyBytes))
		if err != nil {
			http.Error(w, "failed to read body", http.StatusBadRequest)
			return
		}
		registry.BroadcastEphemeral(key, append([]byte(docMessagePrefix), body...))
		w.WriteHeader(http.StatusNoContent)
	}
}

const maxControlBodyBytes = 1 << 10 // a small JSON control object

// handleControl broadcasts a live preview-control update (small JSON body, e.g.
// {"cursor":"caret"} / {"zoom":1.2}) to key's room, tagged with
// controlMessagePrefix. Ephemeral like /scroll and /doc — a transient control
// signal, not the room's content. Powers runtime commands (:MDViewCursor,
// :MDViewZoom) that change the open tab without a reload.
func handleControl(registry *relay.Registry, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		key := r.URL.Query().Get("key")
		if key == "" {
			http.Error(w, "missing key", http.StatusBadRequest)
			return
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, maxControlBodyBytes))
		if err != nil {
			http.Error(w, "failed to read body", http.StatusBadRequest)
			return
		}
		registry.BroadcastEphemeral(key, append([]byte(controlMessagePrefix), body...))
		w.WriteHeader(http.StatusNoContent)
	}
}

// handleDiff fans an incremental content update (a client-tagged envelope) out
// to key's room WITHOUT recording it as the room's last content. Full snapshots
// still flow through /update (LastPayload), so a newly-joined tab is seeded with
// a full document, then receives subsequent diffs — the relay never inspects or
// applies the envelope, it only forwards the bytes. Used by the opt-in
// experimental.line_diff transport; the client reassembles full text from these.
func handleDiff(registry *relay.Registry, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		key := r.URL.Query().Get("key")
		if key == "" {
			http.Error(w, "missing key", http.StatusBadRequest)
			return
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, maxUpdateBodyBytes))
		if err != nil {
			http.Error(w, "failed to read body", http.StatusBadRequest)
			return
		}
		registry.BroadcastEphemeral(key, body)
		w.WriteHeader(http.StatusNoContent)
	}
}

const maxNavHrefBytes = 4 << 10 // clicked hrefs are short paths, not documents

// handleNav is the browser->Neovim bridge for click-to-navigate. On POST the
// browser enqueues the room key and the raw clicked href; on GET Neovim drains
// the queue (it polls while a click-navigate session is active) and resolves
// each href against the source document itself — the relay never touches the
// filesystem or interprets the path, it only carries the event. Token-gated.
func handleNav(queue *relay.NavQueue, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		switch r.Method {
		case http.MethodGet:
			w.Header().Set("Content-Type", "application/json")
			_ = json.NewEncoder(w).Encode(queue.Drain())
		case http.MethodPost:
			key := r.URL.Query().Get("key")
			if key == "" {
				http.Error(w, "missing key", http.StatusBadRequest)
				return
			}
			body, err := io.ReadAll(io.LimitReader(r.Body, maxNavHrefBytes))
			if err != nil {
				http.Error(w, "failed to read body", http.StatusBadRequest)
				return
			}
			href := strings.TrimSpace(string(body))
			if href == "" {
				http.Error(w, "missing href", http.StatusBadRequest)
				return
			}
			queue.Push(relay.NavRequest{Key: key, Href: href})
			w.WriteHeader(http.StatusNoContent)
		default:
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		}
	}
}

const maxScrollbackBytes = 64 // just a "<ratio>" float

// handleScrollback is the browser->Neovim half of bidirectional scrolling. On
// POST the browser overwrites the latest scroll position (a 0..1 ratio) for a
// room; on GET Neovim consumes it (polling while a reverse-scroll session is
// active) and moves its cursor proportionally. Single-slot and consume-once, so
// a stale position never re-applies. Token-gated; the relay never interprets
// the value beyond carrying it.
func handleScrollback(box *relay.ScrollBox, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		switch r.Method {
		case http.MethodGet:
			w.Header().Set("Content-Type", "application/json")
			_ = json.NewEncoder(w).Encode(box.Take())
		case http.MethodPost:
			key := r.URL.Query().Get("key")
			if key == "" {
				http.Error(w, "missing key", http.StatusBadRequest)
				return
			}
			body, err := io.ReadAll(io.LimitReader(r.Body, maxScrollbackBytes))
			if err != nil {
				http.Error(w, "failed to read body", http.StatusBadRequest)
				return
			}
			ratio, err := strconv.ParseFloat(strings.TrimSpace(string(body)), 64)
			if err != nil {
				http.Error(w, "invalid ratio", http.StatusBadRequest)
				return
			}
			if ratio < 0 {
				ratio = 0
			} else if ratio > 1 {
				ratio = 1
			}
			box.Set(relay.ScrollHint{Key: key, Ratio: ratio})
			w.WriteHeader(http.StatusNoContent)
		default:
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		}
	}
}

// handleClose tells every connected preview tab to close itself (the client
// calls window.close() on the closeMessagePrefix signal). This is how mdview
// cooperatively closes tabs in the "default" browser open_mode, where it holds
// no OS process handle for the browser tab. Token-gated; broadcast to all rooms
// since a stop applies to the whole session, not one document. Ephemeral, so a
// tab that connects afterwards is never seeded with a stale close signal.
func handleClose(registry *relay.Registry, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		registry.BroadcastAllEphemeral([]byte(closeMessagePrefix))
		w.WriteHeader(http.StatusNoContent)
	}
}

// handleWS upgrades a browser connection after validating both the Origin
// header (rejects DNS-rebinding / cross-site WebSocket hijacking) and the
// shared token (rejects any process that isn't the plugin's own browser
// tab), then joins the connection to the room for its document key.
func handleWS(registry *relay.Registry, token string, port int) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !relay.IsAllowedOrigin(r.Header.Get("Origin"), port) {
			http.Error(w, "forbidden origin", http.StatusForbidden)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		key := r.URL.Query().Get("key")
		if key == "" {
			http.Error(w, "missing key", http.StatusBadRequest)
			return
		}

		c, err := websocket.Accept(w, r, &websocket.AcceptOptions{
			OriginPatterns: []string{"*"}, // Origin already validated above
		})
		if err != nil {
			return
		}
		defer c.CloseNow()

		ctx := r.Context()
		conn := wsConn{ctx: ctx, c: c}
		registry.Join(key, conn)
		defer registry.Leave(key, conn)

		if payload, ok := registry.LastPayload(key); ok {
			if err := conn.Send(payload); err != nil {
				return
			}
		}

		// Receive-only from the browser's side; all content flows in via POST
		// /update. Reading here just detects disconnects so we clean up the room.
		for {
			if _, _, err := c.Read(ctx); err != nil {
				return
			}
		}
	}
}
