// Command mdview-server is the relay process spawned by the Neovim plugin.
// It authenticates a single trusted Neovim instance (via a shared token
// generated by the Lua side), accepts raw markdown text over HTTP, and fans
// it out over WebSocket to browser tabs watching the same document. It never
// renders markdown or touches HTML — that happens entirely client-side in
// the WASM module, so this process has no code path that turns untrusted
// document content into markup.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"mime"
	"net/http"
	"strconv"
	"strings"

	"nhooyr.io/websocket"

	"github.com/StefanBartl/mdview.nvim/native/server/internal/relay"
)

const maxUpdateBodyBytes = 32 << 20 // 32 MiB ceiling against runaway request bodies
const maxScrollBodyBytes = 256      // scroll payload is just "<line>/<total>"

// scrollMessagePrefix tags a WebSocket message as a scroll-position ping
// rather than document content, so the client's single onmessage handler can
// tell them apart without a JSON envelope. \x01 is a non-printable control
// byte that can never appear in typed Markdown text, so there's no
// ambiguity with real content.
const scrollMessagePrefix = "\x01"

// closeMessagePrefix tags a WebSocket message as a "close this tab now" signal.
// The client calls window.close() on receipt. Used to cooperatively close
// preview tabs in the "default" browser open_mode, where mdview holds no OS
// process handle for the tab and so can't close it any other way. \x02, like
// \x01, is a control byte that can never appear in typed Markdown.
const closeMessagePrefix = "\x02"

// wsConn adapts a *websocket.Conn to relay.Conn so relay.Registry stays
// decoupled from the WebSocket library and can be tested without a network.
type wsConn struct {
	ctx context.Context
	c   *websocket.Conn
}

func (w wsConn) Send(payload []byte) error {
	return w.c.Write(w.ctx, websocket.MessageText, payload)
}

func main() {
	preferredPort := flag.Int("port", 43219, "preferred port to bind on 127.0.0.1")
	webRoot := flag.String("web-root", "dist/client", "directory containing the built client bundle")
	token := flag.String("token", "", "shared session token generated by the Lua caller (required)")
	flag.Parse()

	if *token == "" {
		log.Fatal("--token is required: the Lua caller must generate and pass a session token")
	}

	port, err := relay.FindFreePort(*preferredPort)
	if err != nil {
		log.Fatalf("failed to find free port: %v", err)
	}

	registry := relay.NewRegistry()
	navQueue := relay.NewNavQueue()
	scrollBox := relay.NewScrollBox()
	mime.AddExtensionType(".wasm", "application/wasm")
	fileServer := http.FileServer(http.Dir(*webRoot))

	mux := http.NewServeMux()
	mux.HandleFunc("/health", handleHealth)
	mux.HandleFunc("/update", handleUpdate(registry, *token))
	mux.HandleFunc("/scroll", handleScroll(registry, *token))
	mux.HandleFunc("/diff", handleDiff(registry, *token))
	mux.HandleFunc("/close", handleClose(registry, *token))
	mux.HandleFunc("/nav", handleNav(navQueue, *token))
	mux.HandleFunc("/scrollback", handleScrollback(scrollBox, *token))
	mux.HandleFunc("/clientlog", handleClientLog(*token))
	mux.HandleFunc("/ws", handleWS(registry, *token, port))
	mux.Handle("/", fileServer)

	addr := fmt.Sprintf("127.0.0.1:%d", port)
	// Lua's runner matches this exact line to discover the port; keep the format stable.
	fmt.Printf("Running on http://localhost:%d\n", port)
	fmt.Printf("ws endpoint: ws://localhost:%d/ws\n", port)

	if err := http.ListenAndServe(addr, mux); err != nil {
		log.Fatalf("server error: %v", err)
	}
}

func handleHealth(w http.ResponseWriter, _ *http.Request) {
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte("ok"))
}

const maxClientLogBytes = 8 << 10 // 8 KiB per client log line

// handleClientLog lets the browser client report its own diagnostics
// (connection status, render/theme errors) back to the process. The line is
// printed to stdout with a "[client]" tag; the Lua runner captures the
// relay's stdout into the mdview log buffer, so browser-side problems show up
// in :MDViewShowWebLogs / :MDViewDiagnose without opening devtools. Purely a
// diagnostics sink — it never affects rendering or the room state.
func handleClientLog(token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, maxClientLogBytes))
		if err != nil {
			http.Error(w, "failed to read body", http.StatusBadRequest)
			return
		}
		// One line, control chars stripped, so a hostile page can't inject
		// fake log lines into the captured stream.
		line := strings.Map(func(rr rune) rune {
			if rr == '\n' || rr == '\r' {
				return ' '
			}
			return rr
		}, string(body))
		fmt.Printf("[client] %s\n", line)
		w.WriteHeader(http.StatusNoContent)
	}
}

// handleUpdate accepts the current raw text of a document from the trusted
// Lua process and fans it out to every browser tab watching that key.
func handleUpdate(registry *relay.Registry, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		key := r.URL.Query().Get("key")
		if key == "" {
			http.Error(w, "missing key", http.StatusBadRequest)
			return
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, maxUpdateBodyBytes))
		if err != nil {
			http.Error(w, "failed to read body", http.StatusBadRequest)
			return
		}
		registry.Broadcast(key, body)
		w.WriteHeader(http.StatusNoContent)
	}
}

// handleScroll accepts a "<line>/<total>" cursor-position ping from the
// trusted Lua process and fans it out to every browser tab watching that
// key, tagged with scrollMessagePrefix. Unlike handleUpdate, this does NOT
// update the room's "last content" (BroadcastEphemeral) — a scroll ping is a
// transient signal, not something a newly-joined tab should be seeded with
// in place of the actual document.
func handleScroll(registry *relay.Registry, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		key := r.URL.Query().Get("key")
		if key == "" {
			http.Error(w, "missing key", http.StatusBadRequest)
			return
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, maxScrollBodyBytes))
		if err != nil {
			http.Error(w, "failed to read body", http.StatusBadRequest)
			return
		}
		registry.BroadcastEphemeral(key, append([]byte(scrollMessagePrefix), body...))
		w.WriteHeader(http.StatusNoContent)
	}
}

// handleDiff fans an incremental content update (a client-tagged envelope) out
// to key's room WITHOUT recording it as the room's last content. Full snapshots
// still flow through /update (LastPayload), so a newly-joined tab is seeded with
// a full document, then receives subsequent diffs — the relay never inspects or
// applies the envelope, it only forwards the bytes. Used by the opt-in
// experimental.line_diff transport; the client reassembles full text from these.
func handleDiff(registry *relay.Registry, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		key := r.URL.Query().Get("key")
		if key == "" {
			http.Error(w, "missing key", http.StatusBadRequest)
			return
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, maxUpdateBodyBytes))
		if err != nil {
			http.Error(w, "failed to read body", http.StatusBadRequest)
			return
		}
		registry.BroadcastEphemeral(key, body)
		w.WriteHeader(http.StatusNoContent)
	}
}

const maxNavHrefBytes = 4 << 10 // clicked hrefs are short paths, not documents

// handleNav is the browser->Neovim bridge for click-to-navigate. On POST the
// browser enqueues the room key and the raw clicked href; on GET Neovim drains
// the queue (it polls while a click-navigate session is active) and resolves
// each href against the source document itself — the relay never touches the
// filesystem or interprets the path, it only carries the event. Token-gated.
func handleNav(queue *relay.NavQueue, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		switch r.Method {
		case http.MethodGet:
			w.Header().Set("Content-Type", "application/json")
			_ = json.NewEncoder(w).Encode(queue.Drain())
		case http.MethodPost:
			key := r.URL.Query().Get("key")
			if key == "" {
				http.Error(w, "missing key", http.StatusBadRequest)
				return
			}
			body, err := io.ReadAll(io.LimitReader(r.Body, maxNavHrefBytes))
			if err != nil {
				http.Error(w, "failed to read body", http.StatusBadRequest)
				return
			}
			href := strings.TrimSpace(string(body))
			if href == "" {
				http.Error(w, "missing href", http.StatusBadRequest)
				return
			}
			queue.Push(relay.NavRequest{Key: key, Href: href})
			w.WriteHeader(http.StatusNoContent)
		default:
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		}
	}
}

const maxScrollbackBytes = 64 // just a "<ratio>" float

// handleScrollback is the browser->Neovim half of bidirectional scrolling. On
// POST the browser overwrites the latest scroll position (a 0..1 ratio) for a
// room; on GET Neovim consumes it (polling while a reverse-scroll session is
// active) and moves its cursor proportionally. Single-slot and consume-once, so
// a stale position never re-applies. Token-gated; the relay never interprets
// the value beyond carrying it.
func handleScrollback(box *relay.ScrollBox, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		switch r.Method {
		case http.MethodGet:
			w.Header().Set("Content-Type", "application/json")
			_ = json.NewEncoder(w).Encode(box.Take())
		case http.MethodPost:
			key := r.URL.Query().Get("key")
			if key == "" {
				http.Error(w, "missing key", http.StatusBadRequest)
				return
			}
			body, err := io.ReadAll(io.LimitReader(r.Body, maxScrollbackBytes))
			if err != nil {
				http.Error(w, "failed to read body", http.StatusBadRequest)
				return
			}
			ratio, err := strconv.ParseFloat(strings.TrimSpace(string(body)), 64)
			if err != nil {
				http.Error(w, "invalid ratio", http.StatusBadRequest)
				return
			}
			if ratio < 0 {
				ratio = 0
			} else if ratio > 1 {
				ratio = 1
			}
			box.Set(relay.ScrollHint{Key: key, Ratio: ratio})
			w.WriteHeader(http.StatusNoContent)
		default:
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		}
	}
}

// handleClose tells every connected preview tab to close itself (the client
// calls window.close() on the closeMessagePrefix signal). This is how mdview
// cooperatively closes tabs in the "default" browser open_mode, where it holds
// no OS process handle for the browser tab. Token-gated; broadcast to all rooms
// since a stop applies to the whole session, not one document. Ephemeral, so a
// tab that connects afterwards is never seeded with a stale close signal.
func handleClose(registry *relay.Registry, token string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		registry.BroadcastAllEphemeral([]byte(closeMessagePrefix))
		w.WriteHeader(http.StatusNoContent)
	}
}

// handleWS upgrades a browser connection after validating both the Origin
// header (rejects DNS-rebinding / cross-site WebSocket hijacking) and the
// shared token (rejects any process that isn't the plugin's own browser
// tab), then joins the connection to the room for its document key.
func handleWS(registry *relay.Registry, token string, port int) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !relay.IsAllowedOrigin(r.Header.Get("Origin"), port) {
			http.Error(w, "forbidden origin", http.StatusForbidden)
			return
		}
		if !relay.ValidToken(token, r.URL.Query().Get("token")) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		key := r.URL.Query().Get("key")
		if key == "" {
			http.Error(w, "missing key", http.StatusBadRequest)
			return
		}

		c, err := websocket.Accept(w, r, &websocket.AcceptOptions{
			OriginPatterns: []string{"*"}, // Origin already validated above
		})
		if err != nil {
			return
		}
		defer c.CloseNow()

		ctx := r.Context()
		conn := wsConn{ctx: ctx, c: c}
		registry.Join(key, conn)
		defer registry.Leave(key, conn)

		if payload, ok := registry.LastPayload(key); ok {
			if err := conn.Send(payload); err != nil {
				return
			}
		}

		// Receive-only from the browser's side; all content flows in via POST
		// /update. Reading here just detects disconnects so we clean up the room.
		for {
			if _, _, err := c.Read(ctx); err != nil {
				return
			}
		}
	}
}
